openapi: 3.1.0
x-stoplight:
  id: yqpvor4nca3xa
info:
  title: openapi
  version: '1.0'
servers:
  - url: 'https://talk.worksmobile.com'
    description: TalkURL
paths:
  /p/contact/v3/domain/contacts/my:
    parameters: []
    get:
      summary: Get User Information
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                type: object
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-my-info
      description: Get your own information.
      parameters: []
components:
  schemas: {}
