name: Publish package - pypi

on:
  release:
    types:
      - published
  push:
    branches:
      - develop
      - feature/pypi
    paths:
      - VERSION

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements.txt

      - name: Build
        run: |
          make build

  pypi:
    if: ${{ github.event_name == 'release' }}
    needs: setup
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/line-works-sdk/
    steps:
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}

  test-pypi:
    if: ${{ github.event_name == 'push' }}
    needs: setup
    runs-on: ubuntu-latest
    environment:
      name: test-pypi
      url: https://test.pypi.org/project/line-works-sdk/
    steps:
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
