name: Publish package - pypi

on:
  release:
    types:
      - published
  push:
    branches:
      - develop
      - feature/pypi
    paths:
      - VERSION

jobs:
  pypi:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/line-works-sdk/
    steps:
      - uses: actions/checkout@v4

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}

  test-pypi:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    environment:
      name: test-pypi
      url: https://test.pypi.org/project/line-works-sdk/
    steps:
      - uses: actions/checkout@v4

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
